apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fiap-producao-ingress
spec:
  rules:
    - host: fiap-producao.example.com  # Substitua pelo dom√≠nio desejado
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fiap-producao-service
                port:
                  number: 80
